name: Cypress CI
# on:
#   schedule:
#     - cron: '2 */4 * * *'
#   push:
#     branches:
#       - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      - name: Cypress run        
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
